version: '2'
services:
    tornado:
        build: .
        ports:
            - "4000:8888"
        volumes:
            - .:/app
        command: bash -c "./wait-for-it.sh kafka:9092 && pypy3 server.py"
        depends_on:
            - kafka

    kafka:
        image: spotify/kafka
