version: '2'
services:
    tornado:
        build: ./tornado
        ports:
            - "4000:8888"
        volumes:
            - ./tornado:/app
        command: bash -c "./wait-for-it.sh cassandra:9042 && ./wait-for-it.sh kafka:9092 && ./wait-for-it.sh mongo:27017 && ./wait-for-it.sh elastic:9200 && pypy3 server.py"
        depends_on:
            - kafka
            - mongo
            - elastic
            - couchdb
            - rabbitmq
            - postgres

    kafka:
        image: wurstmeister/kafka
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9092
        depends_on:
            - zookeeper

    zookeeper:
        image: wurstmeister/zookeeper

    mongo:
        image: mongo:3

    elastic:
        image: elasticsearch:2

    couchdb:
        image: couchdb:1.6
        ports:
            - "5984:5984"

    rabbitmq:
        image: rabbitmq:3

    postgres:
        image: postgres:9
        volumes:
            - ./postgres.d/tables.sql:/docker-entrypoint-initdb.d/tables.sql
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test

    cassandra:
        image: cassandra:3

